/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutSettings: typeof import('./src/components/AboutSettings.vue')['default']
    AppearanceSettings: typeof import('./src/components/AppearanceSettings.vue')['default']
    AsrInstallProgress: typeof import('./src/components/AsrInstallProgress.vue')['default']
    AsrSettings: typeof import('./src/components/AsrSettings.vue')['default']
    BrowserLibraryPanel: typeof import('./src/components/BrowserLibraryPanel.vue')['default']
    BrowserTab: typeof import('./src/components/BrowserTab.vue')['default']
    ChangesTab: typeof import('./src/components/ChangesTab.vue')['default']
    ChatPanel: typeof import('./src/components/ChatPanel.vue')['default']
    CitationCard: typeof import('./src/components/CitationCard.vue')['default']
    Composer: typeof import('./src/components/Composer.vue')['default']
    ExtensionsSettings: typeof import('./src/components/ExtensionsSettings.vue')['default']
    FilesTab: typeof import('./src/components/FilesTab.vue')['default']
    Icon: typeof import('./src/components/Icon.vue')['default']
    MarkdownView: typeof import('./src/components/MarkdownView.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    ModelsSettings: typeof import('./src/components/ModelsSettings.vue')['default']
    PiCliSetup: typeof import('./src/components/PiCliSetup.vue')['default']
    PreviewTab: typeof import('./src/components/PreviewTab.vue')['default']
    ProviderIcon: typeof import('./src/components/ProviderIcon.vue')['default']
    RightPane: typeof import('./src/components/RightPane.vue')['default']
    SendQueueBar: typeof import('./src/components/SendQueueBar.vue')['default']
    SessionSidebar: typeof import('./src/components/SessionSidebar.vue')['default']
    SkillsSettings: typeof import('./src/components/SkillsSettings.vue')['default']
    SplitRoot: typeof import('./src/components/SplitRoot.vue')['default']
    TerminalTab: typeof import('./src/components/TerminalTab.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
    VoiceRecordBar: typeof import('./src/components/VoiceRecordBar.vue')['default']
    WelcomeView: typeof import('./src/components/WelcomeView.vue')['default']
  }
}
